# Generated by Django 5.0.7 on 2024-07-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_rename_precio_zona_costoenvio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zona',
            old_name='descripcion',
            new_name='descripcion_zona',
        ),
        migrations.RenameField(
            model_name='zona',
            old_name='titulo',
            new_name='nombre_zona',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='disponible',
        ),
    ]
