# Generated by Django 5.0.7 on 2024-07-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_stock_stockk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_masas', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stockk',
        ),
    ]
