# Generated by Django 5.0.7 on 2024-08-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_stock_created_at_stock_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad_masas',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
