# Generated by Django 5.0.7 on 2024-07-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='masasxunidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
