# Generated by Django 5.0.7 on 2024-08-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_masasxunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='masasxunidad',
            field=models.FloatField(),
        ),
    ]
