# Generated by Django 5.0.7 on 2024-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_producto_masasxunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Pizza', max_length=75),
            preserve_default=False,
        ),
    ]
