# Generated by Django 5.0.7 on 2024-10-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
