# Generated by Django 5.0.7 on 2024-07-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('max_pedidos', models.IntegerField(default=10)),
                ('pedidos_actuales', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.turno'),
        ),
    ]
