# Generated by Django 5.0.7 on 2024-07-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_turno_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='hora',
            new_name='horario',
        ),
    ]
