# Generated by Django 5.0.7 on 2024-07-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_pedido_created_at_pedido_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('tomado', 'Tomado'), ('en_proceso', 'En Proceso'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='tomado', max_length=15),
        ),
    ]
