# Generated by Django 5.0.7 on 2024-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='medio_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia/MP', 'Transferencia/MP')], default='Efectivo', max_length=25),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('Retiro', 'Retiro por local'), ('Envio', 'Envio a domicilio')], default='Retiro', max_length=25),
        ),
    ]
